# Generated by Django 4.2.6 on 2023-10-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=122)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('color', models.CharField(default='red', max_length=50)),
                ('sensor_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sensor_created'],
                'get_latest_by': ['sensor_created'],
            },
        ),
        migrations.CreateModel(
            name='SensorReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('steam_injection', models.FloatField()),
                ('reading_created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.sensors')),
            ],
            options={
                'ordering': ['-reading_created'],
                'get_latest_by': ['reading_created'],
            },
        ),
    ]
